# -*- coding: utf-8 -*-
"""PIAIC74044_ASSIGNMENT2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z1aYoFVOwLrYqO_-79R-dWLt7BNpb6j5
"""

### NUMPY ASSIGNMENT#02
                                           ###MUHAMMAD ASIF
                                           ### PIAIC#74044
import numpy as np

#Question:1
#Convert a 1D array to a 2D array with 2 rows?
#array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
X = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
X

#Question:2
#How to stack two arrays vertically?
#Desired Output::
#array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
Y = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
Z = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
Z_1 = np.vstack((Y, Z))
Z_1

#Question:3
#How to stack two arrays horizontally?
#Desired Output::
#array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
Z_1 = np.hstack((X, Y))
Z_1

#Question:4
#How to convert an array of arrays into a flat 1d array?
#Desired Output::
#array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Y_1 = np.arange(0, 10).reshape(1, 10)
Y_1

#Question:5
#How to Convert higher dimension into one dimension?
#Desired Output::
#array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
X_1 = np.arange(0, 15).reshape(1, 5, 3)
Y_1 = X_1.ravel()
Y_1

#Question:6
#Convert one dimension to higher dimension?
#Desired Output::
#array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])
Z_1 = np.reshape(Y_1, (5, 3))
Z_1

#Question:7
#Create 5x5 an array and find the square of an array?
Z_01 = np.arange(0, 25).reshape(5, 5)
Z_01

np.square(Z_01)

#Question:8
#Create 5x6 an array and find the mean?
Z_0 = np.arange(0, 30).reshape(5, 6)
Z_0

np.mean(Z_0)

#Question:9
#Find the standard deviation of the previous array in Q8?
np.std(Z_0)

#Question:10
#Find the median of the previous array in Q8?
np.median(Z_0)

#Question:11
#Find the transpose of the previous array in Q8?
np.transpose(Z_0)

#Question:12
#Create a 4x4 an array and find the sum of diagonal elements?
Y_0 = np.arange(0, 16).reshape(4, 4)
Y_0

np.diag(Y_0)

#Question:13
#Find the determinant of the previous array in Q12?
np.linalg.det(Y_0)

#Question:14
#Find the 5th and 95th percentile of an array?
np.percentile(Y_0, (5, 95))

#Question:15
#How to find if a given array has any null values?
np.where(Y_0 == 0)

